sudo: required
dist: trusty
language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install check subunit

script:
  - pushd array && make test && popd
  - pushd string && make test && popd
